newnaijalatest/Gist/urls.py
from django.urls import path
from . import views

app_name = 'Gist'

urlpatterns = [
    path('gossip', views.gossip, name='gossip'),
    path('relationship', views.relationship, name='relationship'),
    path('celeb', views.celeb, name='celeb'),
    path('wedding', views.wedding, name='wedding'),
    path('all_gist', views.all_gist, name='all_gist'),
    path('display_gist/<slug>/', views.display_gist, name='display_gist'),
    path('<int:gist_id>/', views.saveviewd, name='save'),
    path('add-gist', views.add_gist, name='add-gist'),
    path('unpublished', views.unpublished_guest, name='unpublished'),
    path('edit_gist/<int:pk>/', views.edit_gist, name='edit_gist')
    ]

newnaijalatest/Music/urls.py
from django.urls import path
from . import views

app_name = 'Music'

urlpatterns = [
    path('newsticker', views.newsticker, name='newsticker'),
    path('home', views.home, name='home'),
    path('', views.home1, name='home1'),
    path('testing', views.testing, name='testing'),
    path('songs', views.songs, name='songs'),
    path('gospel', views.gospel, name='gospel'),
    path('hip_hop_rap', views.hip_hop_rap, name='hip_hop_rap'),
    path('hiphop_pop', views.hiphop_pop, name='hiphop_pop'),
    path('others', views.others, name='others'),
    path('video', views.video, name='video'),
    path('video_gospel', views.video_gospel, name='video_gospel'),
    path('video_hiphop_rap', views.video_hiphop_rap, name='video_hiphop_rap'),
    path('video_hiphop_pop', views.video_hiphop_pop, name='video_hiphop_pop'),
    path('video_others', views.video_others, name='video_others'),
    path('song_download/<slug>/', views.song_download, name='song_download'),
    path('video_download/<slug>/', views.video_download, name='video_download'),
    path('video_download/<slug>/', views.video_download, name='video_download'),
    path('add_music', views.add_music, name='add-music'),
    path('add_audio/<music_id>', views.add_audio, name='add-audio'),
    path('Add Video/<music_id>', views.add_video, name='add-video'),
    path('add_mixtape', views.add_mixtape, name='add_mixtape'),
    path('mixtape', views.mixtape, name='mixtape'),
    path('music_mixtape/<slug>/', views.play_mixtape, name='music_mixtape'),
    path('save_commment', views.save_comment, name='save_comment'),
    path('commment', views.display_comment, name='display_comment'),
    path('unplished_mixtape', views.unpublished_mixtape, name='unpublished_mixtape'),
    path('edit_news/<int:pk>/', views.edit_mixtape, name='Detailview'),
    path('unpublished_music', views.unpublished_music, name='unpublished_music'),
    path('edti_music/<int:pk>/', views.edit_music, name='edit_music'),
    path('unpublished_audio', views.unpublished_audio, name='unpublished_audio'),
    path('edti_audio/<int:pk>/', views.edit_audio, name='edit_audio'),
    path('unpublished_video', views.unpublished_video, name='unpublished_video'),
    path('edit_video/<int:pk>/+', views.edit_video, name='edit_video'),
    path('audiocount', views.audiocount, name='audiocount'),
    path('testes', views.debf.as_view(), name='debf')


]

newnaijalatest/NaijaLatest/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('__debug__/', include(debug_toolbar.urls)),
    path('Frontend/', include('Frontend.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('', include('Music.urls')),
    path('Gist/', include('Gist.urls')),
    path('News/', include('News.urls')),
    path('Profile/', include('Profile.urls')),
    path('oauth', include('social_django.urls', namespace='social')),
    path('TalkZone', include('TalkZone.urls')),
    path('Mysteries', include('Mysteries.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('ads/', include('ads.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ]+ urlpatterns

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newnaijalatest/Music/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from datetime import datetime
from .models import Music, Video, Audio, Mixtape, Comments, AudioCount, VideoCount, Confirmemail, Lyrics, dont_eat_baby_food
from django.core.mail import EmailMessage
from django.utils.http import urlsafe_base64_decode
from django.http import Http404, HttpResponseRedirect
from Gist.models import GistPost
from News.models import NewsPosts
from django.db.models import Q
from Profile.models import ProfilePic
from django.http import Http404
from .forms import Addmusic, Addaudio, Addvideo, AddMixtape, EditMixtape, Editmusic, Editaudio, Editvideo
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from hitcount.views import HitCountDetailView
from django.views.generic import ListView

class PostCountHitDetailView(HitCountDetailView):
    model = Video        # your model goes here
    count_hit = True


def home(request):

    time = datetime.now()
    day = time.strftime("%A")
    hour = time.hour
    if hour < 12:
        message = "Good Morning"
    elif 12 <= hour < 16:
        message = "Good afternoon"
    else:
        message = "Good Evening"

    first_six = Music.objects.all().order_by('-id')[:6]
    first_twelve = Music.objects.all().order_by('-id')[6:9]

    print(first_six)
    context = {'time': time, 'message': message, 'day': day, 'first_six': first_six, 'first_twelve':first_twelve }
    template = 'Music/home.html'
    return render(request, template, context)

class debf(ListView):
    context_object_name = 'debf_list'
    template_name = 'Music/testes.html'
    queryset = dont_eat_baby_food.objects.all().order_by('-id')




def newsticker(request):
    template = 'Music/newsticker.html'
    return render(request, template)


def home1(request):
    #video
    first = Video.objects.all().filter(publish=True).order_by('-id')[:1]
    second = Video.objects.all().filter(publish=True).order_by('-id')[1:2]
    third = Video.objects.all().filter(publish=True).order_by('-id')[2:3]
    #forth = Music.objects.all().order_by('-id')[3:4]
    #first_twelve = Music.objects.all().order_by('-id')[6:9]
    first_ten_song = Audio.objects.all().filter(publish=True).order_by('-id')[3:11]
    videos = Video.objects.all().filter(publish=True).order_by('-id')[3:11]
    #from News
    first_slide = NewsPosts.objects.all().filter(publish=True).order_by('-id')[:1]
    second_slide = NewsPosts.objects.all().filter(publish=True).order_by('-id')[1:2]
    third_slide = NewsPosts.objects.all().filter(publish=True).order_by('-id')[2:3]
    forth_slide = NewsPosts.objects.all().filter(publish=True).order_by('-id')[3:4]
    fifth_slide = NewsPosts.objects.all().filter(publish=True).order_by('-id')[4:5]
    sixth_slide = NewsPosts.objects.all().filter(publish=True).order_by('-id')[5:6]
    news = NewsPosts.objects.all().filter(publish=True).order_by('-id')[6:9]

    #Gist
    slide0ne = GistPost.objects.all().filter(publish=True).order_by('-id')[:1]
    slidetwo = GistPost.objects.all().filter(publish=True).order_by('-id')[1:2]
    slidethree = GistPost.objects.all().filter(publish=True).order_by('-id')[2:3]
    slidefour = GistPost.objects.all().filter(publish=True).order_by('-id')[3:4]
    slidefive = GistPost.objects.all().filter(publish=True).order_by('-id')[4:5]
    slidesix = GistPost.objects.all().filter(publish=True).order_by('-id')[5:6]
    gist = GistPost.objects.all().filter(publish=True).order_by('-id')[6:9]
    #Songs
    one = Audio.objects.all().filter(publish=True).order_by('-id')[:1]
    two = Audio.objects.all().filter(publish=True).order_by('-id')[1:2]
    three = Audio.objects.all().filter(publish=True).order_by('-id')[2:3]

    #print(first_six)
    context = {'videos': videos, 'first': first, 'second': second, 'third': third, 'first_ten_song': first_ten_song,
               'first_slide': first_slide, 'second_slide': second_slide, 'third_slide': third_slide,
               'forth_slide': forth_slide, 'fifth': fifth_slide, 'sixth': sixth_slide, 'slideone': slide0ne,
               'slidetwo': slidetwo, 'slidethree': slidethree, 'slidefour': slidefour, 'one': one, 'two': two,
               'three': three, 'news': news, 'gist': gist, 'slidefive': slidefive, 'slidesix': slidesix}

    template = 'Music/home1.html'
    return render(request, template, context)


def testing(request):

    new = NewsPosts.objects.all().order_by('-id')
    page = request.GET.get('page', 1)
    paginator = Paginator(new, 20)
    try:
        newss = paginator.page(page)
    except PageNotAnInteger:
        newss = paginator.page(2)
    except EmptyPage:
        newss = paginator.page(paginator.num_pages)
    context = {'newss': newss, 'new': new}
    template = 'Music/testing.html'
    return render(request, template, context)


def songs(request):
    song = Audio.objects.all().filter(publish=True).order_by('-id')
    paginator = Paginator(song, 20)
    page = request.GET.get('page', 1)
    try:
        songss = paginator.page(page)
    except PageNotAnInteger:
       songss = paginator.page(1)
    except EmptyPage:
        songss = paginator.page(paginator.num_pages)
    #second_songs = Audio.objects.all().order_by('-id')[12:]
    template = 'Music/songs.html'
    context = {'songss': songss}
    return render(request, template, context)


def gospel(request):
    first_fifteen_gospel = Audio.objects.all().filter(Q(music__genre='Christian/Gospel') | Q(music__genre='R&B/soul')
                                                      ).order_by('-id')[:15]
    template = 'Music/gospel.html'
    context = {'first_fifteen_gospel': first_fifteen_gospel}
    return render(request, template, context)


def hip_hop_rap(request):
    first_twelve_hip_hop_rap = Audio.objects.all().filter(music__genre='Hip-Hop/Rap').order_by('-id')[:12]
    second_hip_hop_rap = Audio.objects.all().filter(music__genre='Hip-Hop/Rap').order_by('-id')[12:]
    template = 'Music/hiphoprap.html'
    context = {'first_twelve_hip_hop_rap': first_twelve_hip_hop_rap, 'second_hip_hop_rap': second_hip_hop_rap}
    return render(request, template, context)

def hiphop_pop(request):
    hiphop_pop = Audio.objects.all().filter(Q(music__genre='Hip-Hop') | Q(music__genre='Pop')).order_by('-id')[:15]
    template = 'Music/hiphop-pop.html'
    context = {'hiphop_pop': hiphop_pop}
    return render(request, template, context)

def others(request):
    genres = ['Christian/Gospel', 'Hip-Hop/Rap', 'R&B/Soul', 'Hip-Hop', 'Pop']
    song_others = Audio.objects.all().filter(~Q(music__genre__in=genres)).order_by('-id')[:12]
    template = 'Music/song-others.html'
    context = {'song_others': song_others}
    return render(request, template, context)


def video(request):
    videos = Video.objects.all().filter(publish=True).order_by('-id')
    paginator = Paginator(videos, 20)
    page = request.GET.get('page', 1)
    try:
        all_video = paginator.page(page)
    except PageNotAnInteger:
        all_video = paginator.page(1)
    except EmptyPage:
        all_video = paginator.page(paginator.num_pages)

    template = 'Music/video.html'
    context = {'all_video': all_video}
    return render(request, template, context)


def video_gospel(request):
    vedeo_gospel = Video.objects.all().filter(Q(music__genre='Christian/Gospel') | Q(music__genre='R&B/soul')
                                                      ).order_by('-id')[:15]
    vedeo_gospel2 = Video.objects.all().filter(Q(music__genre='Christian/Gospel') | Q(music__genre='R&B/soul')
                                              ).order_by('-id')[15:]
    template = 'Music/video_gospel.html'
    context = {'vedeo_gospel':  vedeo_gospel, 'vedeo_gospel2': vedeo_gospel2}
    return render(request, template, context)


def video_hiphop_rap(request):
    video_hiphop_rap = Video.objects.all().filter(music__genre='Hip-Hop/Rap').order_by('-id')[:12]
    template = 'Music/video_hiphop_rap.html'
    context = {'video_hiphop_rap': video_hiphop_rap}
    return render(request, template, context)


def video_hiphop_pop(request):
    video_hiphop_pop = Video.objects.all().filter(Q(music__genre='Hip-Hop') | Q(music__genre='Pop')).order_by('-id')[:15]

    template = 'Music/video_hiphop_pop.html'
    context = {'video_hiphop_pop': video_hiphop_pop}
    return render(request, template, context)


def video_others(request):
    genres = ['Christian/Gospel', 'Hip-Hop/Rap', 'R&B/Soul', 'Hip-Hop', 'Pop']
    video_others = Video.objects.all().filter(~Q(music__genre__in=genres)).order_by('-id')[:12]
    template = 'Music/video_others.html'
    context = {'video_others': video_others}
    return render(request, template, context)


def song_download(request, slug):
    if request.method == 'POST':
        count = request.Get.get('count')
        add = AudioCount.objects.create(number_of_download=count)
        add.save()
    try:
        featured_artist = Audio.objects.get(slug=slug)
        artist = featured_artist.music.artist
        first_six_artist_song = Audio.objects.filter(~Q(slug=slug), music__artist=artist, publish=True).order_by('-id')[:6]
        play_audio = Audio.objects.filter(slug=slug)
    except Music.DoesNotExist:
        raise Http404("can't play or download song")
    return render(request, 'Music/song_download.html', {'play_audio': play_audio,
                                                        'first_six_artist_song': first_six_artist_song,
                                                        'featured_artist': featured_artist})


def video_download(request, slug):
    if request.method == 'POST':
        count = request.Get.get('count')
        add = VideoCount.objects.create(number_of_download=count)
        add.save()
    try:
        play_video = Video.objects.get(slug=slug)
        featured_artist = Video.objects.get(slug=slug)
        artist = featured_artist.music.artist

newnaijalatest/Music/templates/Music/gospel.html
{% extends 'Frontend/base.html' %}
<title> {% block title %}Gospel{% endblock %}</title>

     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

{% block body %}
  {% load static %}


   <div class="container" style="background-color:white; margin-top: 0.5%">
   <div class="row">
    {% for songs in  first_fifteen_gospel %}
                <div class="col-md-4 " style="padding-left: 1px;padding-right: 1px">
                    <div class="card card-img-top ">
                        <a href="{% url 'Music:song_download' songs.id %}">
                            <img src="{{ songs.cover_image.url }}" class="img-fluid" style="height: 160px; width: 1000px;">
                            <h6 style="margin-top: -15%;color: #DC73FF">{{ songs.music.song_title }}</h6>
                        </a>
                        <a href="#" style="color: darkgray;">
                            <h6 style="font-family:'Times New Roman'; "><strong>Artist</strong><strong style="color:black ">:</strong> {{songs.music.artist }}</h6>
                            <h6 style="font-family:'Times New Roman'; ">Released<strong style="color:black ">:</strong> {{ songs.music.released_Year }}</h6>
                        </a>
                        <div class="row">
                            <div class="col-md-4">
                                <a href="#" style="margin-left: 5px;color: darkgray"> <i class="fas fa-share-alt" style="color: #F0F0F0"></i>&nbsp;7</a>
                            </div>
                            <div class="col-md-4">
                                <a href="#" style="margin-left: 5px;color: darkgray"> <i class="fas fa-download" style="color: #F0F0F0"></i></i>&nbsp;7</a>
                            </div>
                             <div class="col-md-4" style="color: darkgray">
                                 <i class="fas fa-eye" style="color: #F0F0F0"></i>7
                             </div>

                        </div>

                    </div>

                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}

    </div>
   </div>
{% endblock %}

newnaijalatest/Music/templates/Music/hee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>

</html>

newnaijalatest/Music/templates/Music/hiphop-pop.html
{% extends 'Music/../../../Frontend/templates/Frontend/base.html' %}
<title> {% block title %}Hip-Hop-Rap{% endblock %}</title>

     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

{% block body %}
  {% load static %}


   <div class="container" style="background-color:white; margin-top: 0.5%">
   <div class="row">
    {% for songs in  hiphop_pop %}
                <div class="col-md-4 " style="padding-left: 1px;padding-right: 1px">
                    <div class="card card-img-top ">
                        <a href="{% url 'Music:song_download' songs.id %}">
                            <img src="{{ songs.cover_image.url }}" class="img-fluid" style="height: 160px; width: 1000px;">
                            <h6 style="margin-top: -15%;color: #DC73FF">{{ songs.music.song_title }}</h6>
                        </a>
                        <a href="#" style="color: darkgray;">
                            <h6 style="font-family:'Times New Roman'; "><strong>Artist</strong><strong style="color:black ">:</strong> {{songs.music.artist }}</h6>
                            <h6 style="font-family:'Times New Roman'; ">Released<strong style="color:black ">:</strong> {{ songs.music.released_Year }}</h6>
                        </a>
                        <div class="row">
                            <div class="col-md-4">
                                <a href="#" style="margin-left: 5px;color: darkgray"> <i class="fas fa-share-alt" style="color: #F0F0F0"></i>&nbsp;7</a>
                            </div>
                            <div class="col-md-4">
                                <a href="#" style="margin-left: 5px;color: darkgray"> <i class="fas fa-download" style="color: #F0F0F0"></i></i>&nbsp;7</a>
                            </div>
                             <div class="col-md-4" style="color: darkgray">
                                 <i class="fas fa-eye" style="color: #F0F0F0"></i>7
                             </div>

                        </div>

                    </div>

                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}

    </div>
   </div>
{% endblock %}

newnaijalatest/Music/templates/Music/music_mixtape.html
{% extends 'Music/../../../Frontend/templates/Frontend/base.html' %}
<title> {% block title %}News View{% endblock %}</title>
{% block extra_head_tags %}
{% for gist in gist %}
<meta property="og:url"           content="{{ ref_url }}/{{gist.title  }}" /><meta property="og:type"          content="website" />

  <meta property="og:title"         content="{{ gist.title }}" />
  <meta property="og:description"   content="{{ gist.description }}" />
  <meta property="og:image"         content="{{ ref_url }}{{ gist.cover_image.url }}" />
    {% endfor %}
{% endblock %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

{% block body %}
  {% load static %}

  <div class="container" style="background-color:white; margin-top: 0.5%">


       <div class="row">
            <div class="col-sm-12" >
                <a href="#" class="col-sm-12 btn btn-dark"><strong>[MIXTAPE]: </strong>{{mixtape.tape_name |safe}}</a>
                <h6 style="color:#535362;margin-top: 5%"><strong>Posted on: </strong>{{mixtape.uploaded_at.date }}</h6>
                <h6 style="color: #535362; margin-top: 5%">By <strong>{{ mixtape.user.username }}</strong></h6>
            </div>
        </div><br>


  <div class="row">
        <div class="col-lg-12">
            <div class="too" style="float: right">
                {% for gist in gist %}
                <a href="https://www.facebook.com/sharer/sharer.php?u={{ ref_url }}" target="_blank">
                    <i class="fab fa-facebook-square fa-2x" style="color: #3B5998"></i>
                </a>
                {% endfor %}
                <a href="" ><i class="fab fa-google-plus-square fa-2x" style="color: #dc4e41"></i></a>
                <a href=""  ><i class="fab fa-twitter-square fa-2x" style="color: #55acee"></i></a>
                <a href="" ><i class="fab fa-linkedin fa-2x" style="color:  #0077B5"></i></a>
                <a href=""><i class="fab fa-whatsapp-square fa-2x" style="color: #25d366"></i></a>
            </div>
        </div>
    </div>
  <hr>


  <div class="row">
      <div class="col-lg-12">
          <h6 style="color: #535362">{{mixtape.dj_description |safe}}</h6>
      </div>
  </div>

  <hr>

  <div class="row" style="margin-top: 8%">
      <div class="col-lg-12 col-sm-12">
          <img src="{{ mixtape.tape_image.url }}" class="img-fluid center-block" style="height: 210px;width: 1000px">
          <audio id="myAudio">
              <source src="{{mixtape.tape.url }}" type="audio/mpeg">
              Your browser does not support the audio element.
          </audio>
         <button onclick="playAudio()" type="button" style="margin-top: 5%">Play Audio</button>
          <button onclick="pauseAudio()" type="button" style="margin-top: 5%">Pause Audio</button>
          <button  type="button" style="margin-top: 1%"><a href="{{mixtape.tape.url }}" style="text-decoration: none;color: black"
                                                           download="{{ mixtape.tape.url }}"> Download Audio</a>
          </button>
      </div>
  </div>
    <div class="row" style="margin-top: 5%">
    <div class="col-lg-6">
        <h6>{{ mixtape.tracks |safe}}</h6>
    </div>
    </div>

<div class="row" style="margin-top: 10%">
    <div class="col-12 bg-dark">
        <h6 style="text-align: center; color:white "><strong>RELATED MIXTAPES</strong></h6>
    </div>
</div>
  <div class="row" style="margin-top: 10%">
    {% for tapes in  related_mixtape %}
                <div class="col-md-6 " style="padding-left: 10px;padding-right: 10px">
                        <a href="{% url 'Music:music_mixtape' tapes.slug %}" style="text-decoration: none">
                            <img src="{{ tapes.tape_image.url }}" class="img-fluid" style="height: 160px; width: 1000px;">
                        </a>
                    <h2></h2>
                    <h2></h2>
                         <a href="{% url 'Music:music_mixtape' tapes.slug %}" style="text-decoration: none">
                            <h6 style="font-family:'Times New Roman'; color:#535362 "><strong>{{ tapes.tape_name|safe }}</strong></h6>
                        </a>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
    {% endfor %}
  </div>

      <div class="row">
       <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <!-- Your share button code -->
  <div class="fb-share-button"
       data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-size="small"
       data-mobile-iframe="true">
      <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse"

         class="fb-xfbml-parse-ignore"> <i class="fab fa-facebook-square fa-2x" style="color: #3B5998"></i>
      </a>
  </div>
      </div>
  <div class="col-lg-12" style="margin-top: 4%">

          <a class="btn btn-dark" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            COMMENT HERE
          </a>
            <div class="collapse" id="collapseExample" style="margin-top: 2%">
              <div class="card card-body">
                <form class="form-horizontal" method="post" action="{% url 'Music:save_comment' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="hidden" name="mixtape" value="{{mixtape.id }}">
                             <input type="hidden" name="mixtape_slug" value="{{mixtape.slug }}">
                            <div class="row">
                              <label class="col-lg-3 control-label" for="comment" style="color: black">Comment</label>
                              <div class="col-lg-6">
                                  <textarea type="text"  cols="45" rows="8" class="form-control" id="comment" value="{{ comment}}" name="comment" required></textarea>
                              </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                              <label class="col-lg-3 control-label" for="name" style="color: black">Name</label>
                              <div class="col-lg-6">
                                  <input type="text"  class="form-control" id="name" value="{{name }}" name="name" required  >
                              </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                              <div class="col-lg-6">
                                  <button type="submit" class="btn btn-dark" style="color:white;">Post Comment</button>
                              </div>
                            </div>
                        </div>
                    </form>
              </div>
            </div>
        </div>
    {% if comments %}
    <div class="row" style="margin-top: 5%">
    <div class="col-lg-12">
        <div class="col-lg-3 bg-dark" style="height: 30px; border-radius: 3px">
           <strong style="color: white">COMMENTS <i>{{ total }}</i></strong>
        </div>
    </div>
    <div class="col-sm-12" style="margin-top: 2%">
    <div class="row">
        {% for comment in  comments %}
                <div class="col-md-10">
                <div class="card">
                    <div class="row">
                    <div class="col-lg-2" style="margin-top: 2%">
                        <i class="fas fa-user fa-3x float-right"></i>
                    </div>
                    <div class="col-lg-7" style="margin-top: 1%">
                        <h2>{{ comment.name }}</h2>
                        <h6>{{ comment.date }}</h6>
                        <h6>{{ comment.comment }}</h6>
                        <div class="col-lg-12" style="margin-top: 0.5%">
                    </div><br>
                    </div>
                   </div>
            </div>
                </div>
        {% endfor %}
            </div>
    </div>

    </div>
    {% endif %}

  </div>

   <script>
var x = document.getElementById("myAudio");

function playAudio() {
    x.play();
}

function pauseAudio() {
    x.pause();
}
</script>

<script type="text/javascript">
function goFullscreen(id) {
  var element = document.getElementById(id);
  if (element.mozRequestFullScreen) {
    element.mozRequestFullScreen();
  } else if (element.webkitRequestFullScreen) {
    element.webkitRequestFullScreen();
  }
}
</script>

{% endblock %}