newnaijalatest/Gist/urls.py
from django.urls import path
from . import views

app_name = 'Gist'

urlpatterns = [
    path('gossip', views.gossip, name='gossip'),
    path('relationship', views.relationship, name='relationship'),
    path('celeb', views.celeb, name='celeb'),
    path('wedding', views.wedding, name='wedding'),
    path('all_gist', views.all_gist, name='all_gist'),
    path('display_gist/<slug>/', views.display_gist, name='display_gist'),
    path('<int:gist_id>/', views.saveviewd, name='save'),
    path('add-gist', views.add_gist, name='add-gist'),
    path('unpublished', views.unpublished_guest, name='unpublished'),
    path('edit_gist/<int:pk>/', views.edit_gist, name='edit_gist')
    ]

newnaijalatest/NaijaLatest/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('__debug__/', include(debug_toolbar.urls)),
    path('Frontend/', include('Frontend.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('', include('Music.urls')),
    path('Gist/', include('Gist.urls')),
    path('News/', include('News.urls')),
    path('Profile/', include('Profile.urls')),
    path('oauth', include('social_django.urls', namespace='social')),
    path('TalkZone', include('TalkZone.urls')),
    path('Mysteries', include('Mysteries.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('ads/', include('ads.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ]+ urlpatterns

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newnaijalatest/News/urls.py
from django.urls import path
from . import views

app_name = 'News'

urlpatterns = [
    path('politics', views.politics, name='politics'),
    path('sport', views.sport, name='sport'),
    path('entertainment', views.entertainment, name='entertainment'),
    path('all_news', views.all_news, name='all_news'),
    path('display_news/<slug>/', views.display_news, name='display_news'),
    path('addnews', views.add_news, name='addnews'),
    path('review_new', views.unpublished_news, name='review_news'),
    path('edit_news/<int:pk>/', views.edit_news, name='Detailview')
    ]

newnaijalatest/News/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.conf import settings
from  ckeditor.fields import RichTextField, CKEditorWidget
from ckeditor_uploader.fields import RichTextUploadingField

CATEGORY_CHOICES = (
    ('politics', 'POLITICS'),
    ('entertainment', 'ENTERTAINMENT'),
    ('sports', 'SPORT'),
)


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.username, filename)


class Post(models.Model):
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=200, blank=True)
    body = models.TextField()
    category = models.CharField(max_length=15, choices=CATEGORY_CHOICES, default='politics')
    slug = models.SlugField(max_length=200, unique=True)
    cover_image = models.ImageField(upload_to=user_directory_path)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    poster = models.CharField(max_length=30)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='post', on_delete=models.DO_NOTHING)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class NewsPosts(models.Model):
    title = RichTextField(max_length=1000, config_name='special')
    description = RichTextField(max_length=2000, blank=True, config_name='special')
    body = RichTextUploadingField(config_name='default',
                                  external_plugin_resources=[('Youtube',
                                                             '/NaijaLatest/static/ckeditor/ckeditor/plugins/youtube/',
                                                              'plugin.js', )],
                                  )
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='politics')
    slug = models.SlugField(max_length=1000, unique=True)
    cover_picture = models.ImageField(upload_to=user_directory_path, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    speaker = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='newsposts', on_delete=models.DO_NOTHING)
    publish = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(NewsPosts, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

newnaijalatest/News/forms.py
from django import forms
from News.models import NewsPosts


class AddNews(forms.ModelForm):
    class Meta:
        model = NewsPosts
        exclude = {'slug', 'user'}
        fields = ['title', 'description', 'body', 'category', 'cover_picture', 'speaker']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.TextInput(attrs={'class': 'form-control', 'width': '650px'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'cover_picture': forms.FileInput(attrs={'class': 'form-control'}),
            'speaker': forms.TextInput(attrs={'class': 'form-control'}),
        }


class EditNews(forms.ModelForm):
    class Meta:
        model = NewsPosts
        exclude = {'slug', 'user'}
        fields = ['title', 'description', 'body', 'category', 'cover_picture', 'speaker']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.TextInput(attrs={'class': 'form-control', 'width': '650px'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'cover_picture': forms.FileInput(attrs={'class': 'form-control'}),
            'speaker': forms.TextInput(attrs={'class': 'form-control'}),
        }

newnaijalatest/News/views.py
from django.shortcuts import render, redirect
from .models import NewsPosts
from django.db.models import Q
from django.http import Http404
from .forms import AddNews, EditNews
from Profile.models import ProfilePic
from django.contrib import messages
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage


def politics(request):
    first_twelve_politics = NewsPosts.objects.all().filter(category='politics', publish=True).order_by('-id')[:12]
    last_politics = NewsPosts.objects.all().filter(category='politics', publish=True).order_by('-id')[12:]
    template = 'News/politics.html'
    context = {'first_twelve_politics': first_twelve_politics, 'last_politics': last_politics}
    return render(request,template, context)


def sport(request):
    first_tweleve_sports = NewsPosts.objects.all().filter(category='sports', publish=True).order_by('-id')[:12]
    rest_sports = NewsPosts.objects.all().filter(category='sports', publish=True).order_by('-id')[12:]
    template = 'News/sports.html'
    context = {'first_tweleve_sports': first_tweleve_sports, 'rest_sports': rest_sports}
    return render(request, template, context)


def entertainment(request):
    first_tweleve_entertainment = NewsPosts.objects.all().filter(category='entertainment', publish=True).order_by('-id')[:12]
    rest_entertainment = NewsPosts.objects.all().filter(category='entertainment', publish=True).order_by('-id')[12:]
    template = 'News/entertainment.html'
    context = {'first_tweleve_entertainment': first_tweleve_entertainment, 'rest_entertainment': rest_entertainment}
    return render(request, template, context)


def all_news(request):
    news = NewsPosts.objects.all().filter(publish=True).order_by('-id')
    paginator = Paginator(news, 36)
    page = request.GET.get('page', 1)
    try:
        newss = paginator.page(page)
    except PageNotAnInteger:
        newss = paginator.page(1)
    except EmptyPage:
        newss = paginator.page(paginator.num_pages)
    template = 'News/all_news.html'
    context = {'newss': newss}
    return render(request, template, context)


def display_news(request, slug):
    try:
        print(slug)
        news = NewsPosts.objects.filter(slug=slug)
        select_related_date = NewsPosts.objects.get(slug=slug)
        related_date = select_related_date.category
        print(related_date)
        #more_news_three = NewsPosts.objects.filter(~Q(slug=slug), created_on__date=related_date).order_by('-id')[:3]
        more_news = NewsPosts.objects.filter(~Q(slug=slug), publish=True, category=related_date).order_by('-id')[:6]
        template = 'News/display_news.html'
        context = {'news': news, 'select_related_date': select_related_date, 'more_news': more_news}
    except NewsPosts.DoesNotExist:
        raise Http404("No such Post")
    return render(request, template, context)


def add_news(request):
    current_user = request.user
    user_id = current_user.id
    user_type = ProfilePic.objects.get(user=current_user)
    if request.method == 'POST':
        form = AddNews(request.POST, request.FILES)
        if form.is_valid():
            news = form.save(commit=False)
            title = request.POST.get('title')
            qs = NewsPosts.objects.filter(title=title)
            if qs.exists():
                messages.error(request, 'news Title already Exist')
                form = AddNews()
                return redirect('News:addnews', {'form': form})
            else:
                news.user_id = user_id
                news.publish = False
                element_to_replace = ['', '@', '&', '$', '#', "'", '"', '--', ]
                for element in element_to_replace:
                    if element in title:

                        news.slug = title.replace(element, '-')
                form.save()
                messages.success(request, 'News added successfully')
                if user_type.user_type == 'superuser':
                    return redirect('Profile:superuser')
                elif user_type.user_type == 'Special_User':
                    return redirect('Profile:special_user')
                elif user_type.user_type == 'Viewers':
                    return redirect('Profile:viewers')
        else:
            form = AddNews()
            template = 'News/addnews.html'
            messages.warning(request, "form is invalid, check the fields")
            return render(request, template, {
                'form': form
            })
    else:
        form = AddNews()
        template = 'News/addnews.html'
        return render(request, template, {
            'form': form
        })


def unpublished_news(request):
    unpublished = NewsPosts.objects.filter(publish=False)
    template = 'News/unpublished_news.html'
    context = {'unpublished': unpublished}
    return render(request, template, context)


def edit_news(request, pk):
    current_user = request.user
    user_id = current_user.id
    user_type = ProfilePic.objects.get(user=current_user)
    image = NewsPosts.objects.filter(pk=int(pk))
    try:
        instance = NewsPosts.objects.get(pk=int(pk))
    except:
        instance = None

    form = EditNews(instance=instance)
    if request.method == 'POST':
        form = EditNews(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            news = form.save(commit=False)
            title = request.POST.get('title')

            #news.user_id = user_id
            news.publish = True
            element_to_replace = ['', '@', '&', '$', '#', "'", '"', '--', ]
            for element in element_to_replace:
                if element in title:
                    news.slug = title.replace(element, '-')
            news.save()
            messages.success(request, 'News successfully modified')
            if user_type.user_type == 'superuser':
                return redirect('Profile:superuser')
            elif user_type.user_type == 'Special_User':
                return redirect('Profile:special_user')

        # else:
        #     form = EditTalk(instance=instance)
        #     messages.error(request, "form is not valid")
        #     template = 'Talkzone/talkzone_detail.html'
        #     return render(request, template, {
        #         'form': form
        #     })

    template = 'News/edit_news.html'
    messages.error(request, 'something went wrong')
    return render(request, template, {'form': form, 'image': image})

newnaijalatest/News/templates/News/addnews.html
{% extends 'backend/base.html' %}
{% block title %}ADD NEWS {% endblock %}
{% block body %}

    {% load static %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 offset-3">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert" style="background-color: black; box-shadow: 10px 10px 10px;color:darkgray">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                    <p style="color:white">{{ message }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
        <div class="row">
            <div class="col-md-10 offset-1">
                <div class="card">
                    <div class="card-header">
                    <h3 style="text-align: center">Post News</h3>
                    </div>
                     <div class="card-body">
                                <form class="form-group" method="post"  enctype="multipart/form-data">
                             {% csrf_token %}
                                    {{ form.media }}
                                    {{ form }}
                                    {{form.errors }}
                                    <div class="form-group col-sm-12" style="margin-top: 2%">
                                        <button class="btn btn-success pull-right">Submit</button>
                                    </div>
                                </form>

                     </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

newnaijalatest/News/templates/News/all_news.html
{% extends 'Music/../../../Frontend/templates/Frontend/base.html' %}
<title> {% block title %}News{% endblock %}</title>

     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

{% block body %}
  {% load static %}


   <div class="container" style="background-color:white; margin-top: 0.5%">
   <div class="row">
    {% for news in newss %}
                <div class="col-md-6 " style="padding-left: 1px;padding-right: 1px">

                        <a href="{% url 'News:display_news' news.slug %}">
                            <img src="{{ news.cover_picture.url }}" class="img-fluid" style="height: 160px; width: 1000px;">

                        </a>
                        <a href="{% url 'News:display_news' news.slug %}" style="color: #535362; text-decoration: none">{{ news.title | safe }}</a>


                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
   {% if newss.has_other_pages %}
  <ul class="pagination mx-auto text-right" style="padding-right: 0px">
    {% if newss.has_previous %}
      <li class="page-item disabled"><a href="?page={{ newss.previous_page_number }}"  class="page-link">&laquo;</a></li>
    {% else %}
        <li class="page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
    {% endif %}

    {% for i in newss.paginator.page_range %}
      {% if newss.number == i %}
        <li class="page-item active">
            <a href="?page"  class="page-link bg-dark">  <span>{{ i }} <span class="sr-only">(current)</span></span></a></li>
      {% else %}
        <li class="page-item"><a class="page-link bg-dark" href="?page={{ i }}" style="color: white">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if newss.has_next %}
      <li class="page-item">
          <a class="page-link" href="?page={{newss.next_page_number }}">&raquo;</a>
      </li>
    {% else %}
      <li class="page-item page-link disabled">
          <span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

    </div>

   </div>
{% endblock %}

newnaijalatest/News/templates/News/display_news.html
{% extends 'Music/../../../Frontend/templates/Frontend/base.html' %}
<title> {% block title %}News View{% endblock %}</title>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

{% block body %}
  {% load static %}

  <div class="container" style="background-color:white; margin-top: 0.5%">
  {% for news in news %}
       <div class="row">
            <div class="col-lg-4" >
                <a href="#" class="btn btn-dark" role="button">{{ news.category }}</a>
            </div>
            <div class="col-lg-12">
                <strong style="font-family:'Arial Black'; font-size:xx-large;color: #535362">{{ news.title |safe }}</strong>
            </div>
        </div><br>
      <div class="row">
            <div class="col-lg-12">
                <h6>Posted by <strong style="color: #535362">{{ news.speaker |safe}}</strong> on {{ news.created_on | date }}</h6>
            </div>
        </div>
  <!--<div class="row">
      <div class="col-lg-12">
          <h6 style="border:2px solid black;border-radius: 12px;width: 20%; text-align: center">{{ news.category }}</h6>
        <strong style="font-family: 'Arial Black'; font-size: x-large">{{ news.title }}</strong>
      </div>
  </div>--->
  <!--<div class="row" style="margin-top: 1%">
         <div class="col-lg-4">
            <h6>By <strong>{{ news.speaker  |safe}}</strong></h6>
         </div>
          <div class="col-lg-4">
            <h6>On {{news.created_on  }}</h6>
         </div>
          <div class="col-lg-4">
            <div class="row">
                <div class="col-lg-6">
                   <h6><i class="fas fa-eye" style="color: #F0F0F0"></i> 5</h6>
                </div>
                <div class="col-lg-6">
                    <h6><i class="fas fa-share-alt" style="color: #F0F0F0"></i> 8</h6>
                </div>
            </div>
         </div>
  </div>--->
  {% endfor %}
  <div class="row">
        <div class="col-lg-12">
            <div class="too" style="float: right">
                <a href="https://www.facebook.com/sharer/sharer.php?u=http://CodingForEntrepreneurs.com/">
                    <i class="fab fa-facebook-square fa-2x" style="color: #3B5998"></i>
                </a>
                <a href="" ><i class="fab fa-google-plus-square fa-2x" style="color: #dc4e41"></i></a>
                <a href=""  ><i class="fab fa-twitter-square fa-2x" style="color: #55acee"></i></a>
                <a href="" ><i class="fab fa-linkedin fa-2x" style="color:  #0077B5"></i></a>
                <a href=""><i class="fab fa-whatsapp-square fa-2x" style="color: #25d366"></i></a>
            </div>
        </div>
    </div>
  <hr>
  <!--<div class=" row">
        <div class="col-lg-1">
            <h5 style="font-family: 'Arial Black'; font-size: x-large;"><i class="fas fa-share-alt"></i></h5>
        </div>
        <div class="clo-lg-2">
            <a href="https://www.facebook.com/sharer/sharer.php?u=http://CodingForEntrepreneurs.com/">
            <img src="{% static 'image/f.fw.png' %}" class="img-fluid" height="10"/>
        </a>
        </div>
        <div class="clo-lg-2">
            <a href="https://www.facebook.com/sharer/sharer.php?u=http://CodingForEntrepreneurs.com/">
            <img src="{% static 'image/what.fw.png' %}" class="img-fluid" height="10"/>
        </a>
        </div>
        <div class="clo-lg-2">
            <a href="https://www.facebook.com/sharer/sharer.php?u=http://CodingForEntrepreneurs.com/">
            <img src="{% static 'image/ints.fw.png' %}" class="img-fluid" height="10"/>
        </a>
        </div>
        <div class="clo-lg-2">
            <a href="https://www.facebook.com/sharer/sharer.php?u=http://CodingForEntrepreneurs.com/">
            <img src="{% static 'image/linkdn.fw.png' %}" class="img-fluid" height="10"/>
        </a>
        </div>
    </div>---->

 {% for news in news %}
  <div class="row">
      <div class="col-lg-12">
          <img src="{{ news.cover_picture.url }}" class="center-block img-fluid"style="height: 280px; width: 1000px;"/>
      </div>
  </div>
  {% endfor %}
  <hr>
 <!---- {% if more_news_three %}

  <div class="row">
      <div class="col-lg-12">
          <h6>You May Like This........</h6>
      </div>
  </div>
  <div class="col-lg-12">
  <div class="row">
          {% for news in  more_news_three %}
                <div class="col-md-4 " style="padding-left: 1px;padding-right: 1px">

                        <a href="#">
                            <img src="{{ news.cover_picture.url }}" class="img-fluid" style="height: 160px; width: 1000px;">

                        </a>
                        <a href="#">{{ news.title}}</a>

                        <div class="row">
                            <div class="col-md-4">
                                <a href="#" style="margin-left: 5px;color: darkgray"> <i class="fas fa-share-alt" style="color: #F0F0F0"></i>&nbsp;7</a>
                            </div>
                            <div class="col-md-4">

                            </div>
                             <div class="col-md-4" style="color: darkgray">
                                 <i class="fas fa-eye" style="color: #F0F0F0"></i>7
                             </div>

                        </div>



                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}

  </div>
  </div>
  <hr>
  {% endif %}--->
  <div class="row">
      <div class="col-lg-12">
          {% for news in news %}
          <h6 style="font-family: 'Times New Roman';font-size: larger">{{ news.body |safe|linebreaks }}</h6>
          {% endfor %}
      </div>
  </div>
  {% if more_news %}
      {%for news in news%}
          <div class="row">
            <div class="col-lg-4 offset-4" >
                <a href="#" class="btn btn-dark" role="button">More Related {{ news.category }}'s</a>
            </div>
          </div>
      {% endfor %}
  <hr>

  <div class="col-lg-12">
  <div class="row">
              {% for news in more_news %}
                        <div class="row">
                        <div class="col-lg-4">
                        <a href="{% url  'News:display_news' news.slug%}">
                           <img src="{{ news.cover_picture.url }}" class="img-fluid" style="height: 160px; width: 1000px;">
                        </a>
                        </div>
                            <div class="col-lg-8" id="title">
                                <a href="{% url  'News:display_news' news.slug%}" style="text-decoration: none; color:#535362">{{ news.title | safe}}</a>
                                <h6 style="font-family: 'Times New Roman'; color: lightgray">{{ news.description | safe}}</h6>
                            </div>
                            <div class="col-lg-12">
                                <hr style="color: black; height: 5px;">
                            </div>
                        </div>
                        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                    {% endfor %}

            </div><hr>
  </div>
  {% endif %}
  </div>


{% endblock %}

newnaijalatest/News/templates/News/entertainment.html
{% extends 'Music/../../../Frontend/templates/Frontend/base.html' %}
<title> {% block title %}Entertainment{% endblock %}</title>

     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

{% block body %}
  {% load static %}


   <div class="container" style="background-color:white; margin-top: 0.5%">
   <div class="row">
    {% for news in  first_tweleve_entertainment %}
                <div class="col-md-4 " style="padding-left: 1px;padding-right: 1px">

                        <a href="{% url 'News:display_news' news.slug %}">
                            <img src="{{ news.cover_picture.url }}" class="img-fluid" style="height: 160px; width: 1000px;">

                        </a>
                        <a href="{% url 'News:display_news' news.slug %}" style="text-decoration: none; color: #535362">{{ news.title|safe }}</a>





                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}

    </div>
   <div class="row" style="margin-top: 2%">
    <img src="{% static 'image/adon1.fw.png' %}" alt="Third Slide" class="img-fluid"/>
</div>
   <div class="row">
    {% for news in  rest_entertainment %}
                <div class="col-md-4 " style="padding-left: 1px;padding-right: 1px">

                        <a href="{% url 'News:display_news' news.slug %}">
                            <img src="{{ news.cover_picture.url }}" class="img-fluid" style="height: 160px; width: 1000px;">

                        </a>
                        <a href="{% url 'News:display_news' news.slug %}"style="text-decoration: none; color: #535362">{{ news.title|safe }}</a>




                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}

    </div>
   </div>
{% endblock %}

newnaijalatest/News/templates/News/politics.html
{% extends 'Music/../../../Frontend/templates/Frontend/base.html' %}
<title> {% block title %}Politics{% endblock %}</title>

     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

{% block body %}
  {% load static %}


   <div class="container" style="background-color:white; margin-top: 0.5%">
   <div class="row">
    {% for news in  first_twelve_politics %}
                <div class="col-md-4 " style="padding-left: 1px;padding-right: 1px">

                        <a href="{% url 'News:display_news' news.slug %}">
                            <img src="{{ news.cover_picture.url }}" class="img-fluid" style="height: 160px; width: 1000px;">

                        </a>
                        <a href="{% url 'News:display_news' news.slug %}" style="text-decoration: none; color: #535362">{{ news.title| safe }}</a>





                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}

    </div>
   <div class="row" style="margin-top: 2%">
    <img src="{% static 'image/adon1.fw.png' %}" alt="Third Slide" class="img-fluid"/>
</div>
   <div class="row">
    {% for news in last_politics  %}
                <div class="col-md-4 " style="padding-left: 1px;padding-right: 1px">

                        <a href="{% url 'News:display_news' news.slug %}">
                            <img src="{{ news.cover_picture.url }}" class="img-fluid" style="height: 160px; width: 1000px;">

                        </a>
                        <a href="{% url 'News:display_news' news.slug %}"style="text-decoration: none; color: #535362">{{ news.title|safe }}</a>




                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}

    </div>
   </div>
{% endblock %}

newnaijalatest/News/templates/News/sports.html
{% extends 'Music/../../../Frontend/templates/Frontend/base.html' %}
<title> {% block title %}Sport{% endblock %}</title>

     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

{% block body %}
  {% load static %}


   <div class="container" style="background-color:white; margin-top: 0.5%">
   <div class="row">
    {% for news in  first_tweleve_sports %}
                <div class="col-md-4 " style="padding-left: 1px;padding-right: 1px">

                        <a href="{% url 'News:display_news' news.slug %}">
                            <img src="{{ news.cover_picture.url }}" class="img-fluid" style="height: 160px; width: 1000px;">

                        </a>
                        <a href="{% url 'News:display_news' news.slug %}"style="text-decoration: none; color: #535362">{{ news.title|safe }}</a>





                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}

    </div>
   <div class="row" style="margin-top: 2%">
    <img src="{% static 'image/adon1.fw.png' %}" alt="Third Slide" class="img-fluid"/>
</div>
   <div class="row">
    {% for news in  rest_sports %}
                <div class="col-md-4 " style="padding-left: 1px;padding-right: 1px">

                        <a href="{% url 'News:display_news' news.slug %}">
                            <img src="{{ news.cover_picture.url }}" class="img-fluid" style="height: 160px; width: 1000px;">

                        </a>
                        <a href="{% url 'News:display_news' news.slug %}"style="text-decoration: none; color: #535362">{{ news.title|safe }}</a>





                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}

    </div>
   </div>
{% endblock %}