newnaijalatest/Gist/urls.py
from django.urls import path
from . import views

app_name = 'Gist'

urlpatterns = [
    path('gossip', views.gossip, name='gossip'),
    path('relationship', views.relationship, name='relationship'),
    path('celeb', views.celeb, name='celeb'),
    path('wedding', views.wedding, name='wedding'),
    path('all_gist', views.all_gist, name='all_gist'),
    path('display_gist/<slug>/', views.display_gist, name='display_gist'),
    path('<int:gist_id>/', views.saveviewd, name='save'),
    path('add-gist', views.add_gist, name='add-gist'),
    path('unpublished', views.unpublished_guest, name='unpublished'),
    path('edit_gist/<int:pk>/', views.edit_gist, name='edit_gist')
    ]

newnaijalatest/NaijaLatest/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('__debug__/', include(debug_toolbar.urls)),
    path('Frontend/', include('Frontend.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('', include('Music.urls')),
    path('Gist/', include('Gist.urls')),
    path('News/', include('News.urls')),
    path('Profile/', include('Profile.urls')),
    path('oauth', include('social_django.urls', namespace='social')),
    path('TalkZone', include('TalkZone.urls')),
    path('Mysteries', include('Mysteries.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('ads/', include('ads.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ]+ urlpatterns

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newnaijalatest/TalkZone/urls.py
from django.urls import path
from . import views

app_name = 'TalkZone'

urlpatterns = [
    path('talkzone', views.talk_zone, name='talkzone'),
    path('talk_zone_view/<slug>/', views.talk_zone_view, name='talk_zone_view'),
    path('Comment', views.save_comment, name='save_comment'),
    path('commment', views.display_comment, name='display_comment'),
    path('index', views.index, name='index'),
    path('lazy_load_posts', views.lazy_load_posts, name='lazy_load_posts'),
    path('add_talk', views.add_talk, name='add_talk'),
    path('unpublished', views.unpublished_talkzone, name='unpublished'),
    path('edit_talkzone/<int:pk>/', views.edit_talk, name='Detailview')
     ]

newnaijalatest/TalkZone/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.conf import settings
from  ckeditor.fields import RichTextField, CKEditorWidget
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.username, filename)


class TalkZone(models.Model):
    title = RichTextField(max_length=1000, config_name='special')
    slug = models.SlugField(max_length=1000, unique=True)
    description = RichTextField(max_length=2000, config_name='special')
    body = RichTextUploadingField(config_name='default',
                                  external_plugin_resources=[('Youtube',
                                                              '/NaijaLatest/static/ckeditor/ckeditor/plugins/youtube/',
                                                              'plugin.js', )],
                                  )
    cover_image = models.ImageField(upload_to=user_directory_path, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    poster = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='talkzone', on_delete=models.DO_NOTHING)
    publish = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(TalkZone, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Comments(models.Model):
    talk_zone = models.ForeignKey(TalkZone, on_delete=models.DO_NOTHING)
    comment = models.TextField()
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=1000, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

newnaijalatest/TalkZone/forms.py
from django import forms
from TalkZone.models import TalkZone


class AddTalk(forms.ModelForm):
    class Meta:
        model = TalkZone
        exclude = {'slug', 'user'}
        fields = ['title',  'description', 'body', 'cover_image', 'poster']
        widgets = {

            'title': forms.TextInput(attrs={'class': 'form-control'}),

            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.TextInput(attrs={'class': 'form-control', 'width': '650px'}),
            'cover_image': forms.FileInput(attrs={'class': 'form-control'}),
            'poster': forms.TextInput(attrs={'class': 'form-control'}),
        }


class EditTalk(forms.ModelForm):
    class Meta:
        model = TalkZone
        exclude = {'slug', 'user'}
        fields = ['title',  'description', 'body', 'cover_image', 'poster']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),

            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.TextInput(attrs={'class': 'form-control', 'width': '650px'}),
            'cover_image': forms.FileInput(attrs={'class': 'form-control'}),
            'poster': forms.TextInput(attrs={'class': 'form-control'}),
        }

newnaijalatest/TalkZone/views.py
from django.shortcuts import render, redirect
from .models import TalkZone, Comments
from django.conf import settings
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from .forms import AddTalk, EditTalk
from django.contrib import messages
from Profile.models import ProfilePic
from django.views.generic.detail import DetailView


# Create your views here.
def talk_zone(request):
    talk_zone = TalkZone.objects.all().filter(publish=True).order_by('-id')[1:]
    template = 'TalkZone/talk_zone.html'
    context = {'talk_zone': talk_zone}
    return render(request, template, context)


def talk_zone_view(request, slug):
    try:
        talk_zone = TalkZone.objects.get(slug=slug)
        select_related_date = TalkZone.objects.get(slug=slug)
        related_date = select_related_date.created_on.date()
        title = select_related_date.title
        print(related_date)
        one_talk_zone = TalkZone.objects.filter(~Q(slug=slug), created_on__date=related_date, publish=True).order_by('-id')[
                          :1]
        comments = Comments.objects.filter(talk_zone=talk_zone)
        total = comments.count()
        template = 'TalkZone/talk_zone_view.html'
        ref_url = settings.SHARE_TALKZONE_URL
        context = {'talk_zone': talk_zone, 'select_related_date': select_related_date,
                   'one_talk_zone': one_talk_zone, 'title': title, 'ref_url': ref_url,
                   'comments': comments, 'total': total}
    except TalkZone.DoesNotExist:
        raise Http404("No such Post")
    return render(request, template, context)


def save_comment(request):
    if request.method == 'POST':
        talk_zone_id = int(request.POST['talk_zone'])
        slug = request.POST['slug']
        comment = request.POST['comment']
        name = request.POST['name']
        saved_comment = Comments.objects.create(talk_zone_id=talk_zone_id, comment=comment, name=name, slug=slug)
        saved_comment.save()
        # talkzone = TalkZone.objects.get(pk=talk_zone_id)
        return HttpResponseRedirect(reverse('TalkZone:talk_zone_view', kwargs={'slug': slug}))
        # return redirect('TalkZone:talk_zone_view',)


def display_comment(request, slug):
    comment = Comments.objects.filter(talk_zone=slug)
    total = comment.count()
    template = 'TalkZone/talk_zone_view.html'
    context = {'comment': comment, 'total': total}
    return render(request, template, context)


def index(request):
    posts = TalkZone.objects.all()
    return render(request, 'TalkZone/index.html', {'posts': posts})


def lazy_load_posts(request):
    page = request.POST.get('page')
    posts = TalkZone.objects.all()[:5]  # get just 5 posts

    # use Django's pagination
    # https://docs.djangoproject.com/en/dev/topics/pagination/
    results_per_page = 5
    paginator = Paginator(posts, results_per_page)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(2)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    # build a html posts list with the paginated posts
    posts_html = loader.render_to_string('TalkZone/posts.html', {'posts': posts})

    # package output data and return it as a JSON object
    output_data = {'posts_html': posts_html, 'has_next': posts.has_next()}
    return JsonResponse(output_data)


def add_talk(request):
    current_user = request.user
    user_id = current_user.id
    user_type = ProfilePic.objects.get(user=current_user)
    if request.method == 'POST':
        form = AddTalk(request.POST, request.FILES)
        if form.is_valid():
            talks = form.save(commit=False)
            title = request.POST.get('title')
            qs = TalkZone.objects.filter(title=title)
            if qs.exists():
                messages.error(request, 'Title already Exist')
                form = AddTalk()
                return redirect('TalkZone:add_talk', {'form': form})
            else:
                talks.user_id = user_id
                talks.publish = 'False'
                element_to_replace = ['', '@', '&', '$', '#', "'", '"', '--', ]
                for element in element_to_replace:
                    if element in title:
                        talks.slug = title.replace(element, '-')
                form.save()
                messages.success(request, ' Talk Zone successfully added')
                if user_type.user_type == 'superuser':
                    return redirect('Profile:superuser')
                elif user_type.user_type == 'Special_User':
                    return redirect('Profile:special_user')
                elif user_type.user_type == 'Viewers':
                    return redirect('Profile:viewers')
        else:
            form = AddTalk()
            messages.error(request, "form is not valid")
            template = 'TalkZone/add_talk.html'
            return render(request, template, {
                'form': form
            })
    else:
        form = AddTalk()
        template = 'TalkZone/add_talk.html'
        return render(request, template, {
            'form': form
        })


def unpublished_talkzone(request):
    all_unpublished_talkzone = TalkZone.objects.all().filter(publish=False)
    template = 'TalkZone/unpublished.html'
    context = {'all_unpublished_talkzone': all_unpublished_talkzone}
    return render(request, template, context)


def edit_talk(request, pk):
    current_user = request.user
    user_id = current_user.id
    user_profile = ProfilePic.objects.get(user=current_user)
    user_type = user_profile.user_type
    image = TalkZone.objects.filter(pk=int(pk))
    try:
        instance = TalkZone.objects.get(pk=int(pk))
    except:
        instance = None

    form = EditTalk(instance=instance)
    if request.method == 'POST':
        form = EditTalk(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            talks = form.save(commit=False)
            title = request.POST.get('title')

            #talks.user_id = user_id
            talks.publish = True
            element_to_replace = ['', '@', '&', '$', '#', "'", '"', '--', ]
            for element in element_to_replace:
                if element in title:
                    talks.slug = title.replace(element, '-')
            form.save()
            messages.success(request, 'Talk Zone successfully modified')
            if user_type == 'superuser':
                return redirect('Profile:superuser')
            elif user_type == 'Special_User':
                return redirect('Profile:special_user')

        # else:
        #     form = EditTalk(instance=instance)
        #     messages.error(request, "form is not valid")
        #     template = 'Talkzone/talkzone_detail.html'
        #     return render(request, template, {
        #         'form': form
        #     })

    template = 'TalkZone/talkzone_detail.html'
    return render(request, template, {'form': form, 'image': image})

newnaijalatest/TalkZone/templates/TalkZone/add_talk.html
{% extends 'backend/base.html' %}
{% block title %}ADD NEWS {% endblock %}
{% block body %}

    {% load static %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 offset-3">
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert" style="background-color: black;
                 box-shadow: 10px 10px 10px;color:darkgray">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                    <p style="color:white">{{ message }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
        <div class="row">
            <div class="col-md-10 offset-1">
                <div class="card">
                    <div class="card-header">
                        <H6 style="color:darkred"><strong style="color: #0e0e0e">Note:</strong> subtitle should not be grater than 1000 characters and sub-body should not be graeter than 20000 characters.</H6>
                        <hr>
                    <h3 style="text-align: center">Post Talk Zone</h3>
                    </div>
                     <div class="card-body">
                                <form class="form-group" method="post"  enctype="multipart/form-data">
                             {% csrf_token %}
                                    {{ form.media }}
                                    {{ form }}
                                    {{form.errors }}
                                    <div class="form-group col-sm-12" style="margin-top: 2%">
                                        <button class="btn btn-success pull-right">Submit</button>
                                    </div>
                                </form>

                     </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

newnaijalatest/TalkZone/templates/TalkZone/index.html
{% extends 'Music/../../../Frontend/templates/Frontend/base.html' %}
{% load static %}

<!----<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
 <!--<link rel="stylesheet" href="{% static 'bootstrap4/vendor/bootstrap/css/bootstrap.min.css'  %}">--->
    <!---<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-grid.css' %}"/>


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css"
      integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">---->
      <!--<style type="text/css">-->
 /*body {
    background-color: red;
    width: 400px;
    margin: 20px auto;
    font: normal 13px/100% sans-serif;
    color: #444;
}
div {
    display:none;

}
.totop {
    position: fixed;
    bottom: 10px;
    right: 20px;
}*/
/*.totop a {
    display: none;
}
a, a:visited {
    color: #33739E;
    text-decoration: none;
    display: block;
    margin: 10px 0;
}
a:hover {
    text-decoration: none;
}*/
/*#loadMore {
    padding: 10px;
    text-align: center;
    background-color: red;
    color: #fff;
    border-width: 0 1px 1px 0;
    border-style: solid;
    border-color: #fff;
    box-shadow: 0 1px 1px #ccc;
    transition: all 600ms ease-in-out;
    -webkit-transition: all 600ms ease-in-out;
    -moz-transition: all 600ms ease-in-out;
    -o-transition: all 600ms ease-in-out;
}
#loadMore:hover {
    background-color: #fff;
    color: #33739E;
}
      <!--</style>--->
{% block body %}

  <div class="container">
  <div class="col-lg-12">
  {% for post in posts %}
  <div class="row" style="background-color: black">
      <div id="rose" class="col-lg-4" style="background-color: black">
          <a href="" style="background-color: gray">
              <img src="{{post.cover_image.url }}" class="img-fluid" style="height: 120px; width: 100%;">
          </a>
      </div>
      <div class="col-lg-8" style="background-color: #1c7430">
          <a href="" style="color: #535362"><strong>{{ post.subtitle }}</strong></a>
          <h6 style="font-family: 'Times New Roman'; color: lightgray">{{ post.subbody }}
              <strong style="font-family: 'Times New Roman'; font-size: medium">.....</strong></h6>
      </div>
      <div class="col-lg-12" style="background-color: #0c5460">
          <hr style="color: black; height: 5px;">
      </div>
  </div>
      {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}



  {% endfor %}
  </div>


<a href="#" id="loadMore">Load More</a>

<p class="totop">
    <a href="#top">Back to top</a>
</p>
  </div>
{% endblock %}
<!---<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>--->
<!---<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script aria-describedby="{% static 'lazyload/js.js' %}"></script>--->
{% block js %}
<script>
    $(function () {
    $("div.col-lg-4").slice(0, 2).show();
    $("#loadMore").on('click', function (e) {
        e.preventDefault();
        $("div:hidden").slice(0, 2).slideDown();
        if ($("div:hidden").length == 0) {
            $("#load").fadeOut('slow');
        }
        $('html,body').animate({
            scrollTop: $(this).offset().top
        }, 1500);
    });
});

$('a[href=#top]').click(function () {
    $('body,html').animate({
        scrollTop: 0
    }, 600);
    return false;
});

$(window).scroll(function () {
    if ($(this).scrollTop() > 50) {
        $('.totop a').fadeIn();
    } else {
        $('.totop a').fadeOut();
    }
});
    /*(function($) {
  $('#lazyLoadLink').on('click', function() {
    var link = $(this);
    var page = link.data('page');

    $.ajax({
      type: 'post',
      url: '/lazy_load_posts/',
      data: {
        'page': page,
        'csrfmiddlewaretoken': window.CSRF_TOKEN // from index.html
      },
      success: function(data) {
        // if there are still more pages to load,
        // add 1 to the "Load More Posts" link's page data attribute
        // else hide the link
        if (data.has_next) {
            link.data('page', page+1);
        } else {
          link.hide();
        }
        // append html to the posts div
        $('#div').append(data.posts_html);
      },
      error: function(xhr, status, error) {
        // shit happens friends!
      }
    });
  });
}(jQuery));*/
</script>
{% endblock %}

newnaijalatest/TalkZone/templates/TalkZone/posts.html
{% load static %}
{% for post in posts %}
<div>
  <h4>{{ post.subtitle }}</h4>
  <p>{{ post.subbody }}</p>
</div>
{% endfor %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!---<script src="{% static 'bootstrap4/vendor/bootstrap/js/bootstrap.min.js' %}"></script>--->
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>

<script>
    (function($) {
  $('#lazyLoadLink').on('click', function() {
    var link = $(this);
    var page = link.data('page');

    $.ajax({
      type: 'post',
      url: '/lazy_load_posts/',
      data: {
        'page': page,
        'csrfmiddlewaretoken': window.CSRF_TOKEN // from index.html
      },
      success: function(data) {
        // if there are still more pages to load,
        // add 1 to the "Load More Posts" link's page data attribute
        // else hide the link
        if (data.has_next) {
            link.data('page', page+1);
        } else {
          link.hide();
        }
        // append html to the posts div
        $('#div').append(data.posts_html);
      },
      error: function(xhr, status, error) {
        // shit happens friends!
      }
    });
  });
}(jQuery));
</script>

newnaijalatest/TalkZone/templates/TalkZone/talk_zone_view.html
{% extends 'Frontend/base.html' %}
{% block title %}View Talk Zone{% endblock %}

{% block extra_head_tags %}

    <meta property="og:url"           content="{{ ref_url }}/{{talk_zone.title  }}" /><meta property="og:type" content="website" />

  <meta property="og:title"         content="{{ talk_zone.title }}" />
  <meta property="og:description"   content="{{talk_zone.description }}" />
  <meta property="og:image"         content="{{ ref_url }}{{ talk_zone.cover_image.url }}" />

{% endblock %}

{% block body %}
  {% load static %}

    <div class="container">

        <div class="row">
            <div class="col-lg-4" >
                <a href="#" class="btn btn-dark" role="button">Talk Zone</a>
            </div>
            <div class="col-lg-12">
                <strong style="font-family: 'Times New Roman'; font-size:x-large;color: #535362">{{ talk_zone.title|safe }}</strong>
            </div>
        </div><br>
        <div class="row">
            <div class="col-lg-12">
                <h6>Posted by <strong>{{ talk_zone.poster }}</strong> on {{ talk_zone.created_on | date }}</h6>
            </div>
        </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="too" style="float: right">
                <a href=""><i class="fab fa-facebook-square fa-2x" style="color: #3B5998"></i></a>
                <a href="" ><i class="fab fa-google-plus-square fa-2x" style="color: #dc4e41"></i></a>
                <a href=""  ><i class="fab fa-twitter-square fa-2x" style="color: #55acee"></i></a>
                <a href="" ><i class="fab fa-linkedin fa-2x" style="color:  #0077B5"></i></a>
                <a href=""><i class="fab fa-whatsapp-square fa-2x" style="color: #25d366"></i></a>
            </div>
        </div>
    </div>
    <hr>

        <div class="row">
            <div class="col-lg-12">
               <img src="{{talk_zone.cover_image.url }}" class="img-fluid" style="height: 280px; width: 1000px;">
            </div>
        </div><br>
        <div class="row">
            <div class="col-lg-12">
                <strong style="font-family: 'Times New Roman';font-size: large">{{ talk_zone.description |safe }}</strong>
            </div>
        </div><br>
        <div class="row">
            <div class="col-lg-12">
               <h5 style="font-family: 'Times New Roman';font-size: large">{{ talk_zone.body | safe |linebreaks  }}</h5>
            </div>
        </div>

    <hr>
    {% for talk in one_talk_zone %}
        <div class="row">
        <div class="col-md-4 offset-4">
            <strong>SEE ALSO:-</strong>
        </div>
        <div class="col-lg-12">
        <a href="{% url 'TalkZone:talk_zone_view' talk.slug %}" style="font-family: 'Times New Roman';font-size: large;color:darkgray;"><strong> {{ talk.title|safe }}</strong></a>
        </div>
        </div>
    {% endfor %}
    <br><div class="row">
        <div class="col-lg-12">

          <a class="btn btn-dark" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            COMMENT HERE
          </a>
            <div class="collapse" id="collapseExample" style="margin-top: 2%">
              <div class="card card-body">
                <form class="form-horizontal" method="post" action="{% url 'TalkZone:save_comment' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="hidden" name="talk_zone" value="{{ talk_zone.id }}">
                            <input type="hidden" name="slug" value="{{ talk_zone.slug }}">
                            <div class="row">
                              <label class="col-lg-3 control-label" for="comment" style="color: black">Comment</label>
                              <div class="col-lg-6">
                                  <textarea type="text"  cols="45" rows="8" class="form-control" id="comment" value="{{ comment}}" name="comment" required></textarea>
                              </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                              <label class="col-lg-3 control-label" for="name" style="color: black">Name</label>
                              <div class="col-lg-6">
                                  <input type="text"  class="form-control" id="name" value="{{name }}" name="name" required  >
                              </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                              <div class="col-lg-6">
                                  <button type="submit" class="btn btn-dark" style="color:white;">Post Comment</button>
                              </div>
                            </div>
                        </div>
                    </form>
              </div>
            </div>
        </div>
    </div><br>
    {% if comments %}
    <div class="row" style="margin-top: 5%">
    <div class="col-lg-12">
        <div class="col-lg-3 bg-dark" style="height: 30px; border-radius: 3px">
           <strong style="color: white">COMMENTS {{ total }}</strong>
        </div>
    </div>
    <div class="col-sm-12" style="margin-top: 2%">
    <div class="row">
        {% for comment in  comments %}
                <div class="col-md-10">
                <div class="card">
                    <div class="row">
                    <div class="col-lg-2" style="margin-top: 2%">
                        <i class="fas fa-user fa-3x float-right"></i>
                    </div>
                    <div class="col-lg-7" style="margin-top: 1%">
                        <h2>{{ comment.name }}</h2>
                        <h6>{{ comment.date }}</h6>
                        <h6>{{ comment.comment }}</h6>
                        <br>
                    </div>
                   </div>
            </div>
                </div>
        {% endfor %}
            </div>
    </div>

    </div>
    {% endif %}

    </div>
{% endblock %}

newnaijalatest/TalkZone/templates/TalkZone/unpublished.html
{% extends 'backend/base.html' %}
 {% block title %}User Dashboard{% endblock %}

{% block body %}
{% load static %}
    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
     <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <!---<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" >--->
<link rel="stylesheet" href="{% static 'datatable/Buttons-1.5.2/css/buttons.dataTables.min.css' %}" >
<div class="container">
<div class="row">
    <div class="col-sm-6 offset-3" style="border-radius: 5px; background-color:black;">
        <h3 style="color: white;text-align: center">EDIT TALKZONE</h3>
    </div>
</div>
<div class="row" style="margin-top: 2%;box-shadow: 10px 10px 10px">

            {% if all_unpublished_talkzone%}
                <table  id="review_talk" class="display" style="width:100%">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Date</th>
                    <th>User</th>
                    <th>Poster</th>
                    <th>Edit</th>
                </tr>
                </thead>
                <tbody>
                {% for unpublisheds in all_unpublished_talkzone %}
                    <tr>
                    <td>{{ unpublisheds.title | safe }}</td>
                    <td>{{unpublisheds.created_on | date  }}</td>
                    <td>{{ unpublisheds.user.username}}</td>
                    <td>{{ unpublisheds.poster}}</td>
                    <td><a href="{% url 'TalkZone:Detailview' unpublisheds.pk %}" class="btn btn-dark btn-sm" role="button"><i class="far fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>

        {% else %}
    <P>no data found</P>
{% endif %}
        </div>
</div>
     <script src="{% static 'datatable/DataTables-1.10.18/js/jquery.dataTables.min.js' %}" integrity="" ></script>
    <script src="{% static 'datatable/DataTables-1.10.18/js/dataTables.bootstrap.min.js' %}" integrity="" ></script>
    <script src="{% static 'datatable/DataTables-1.10.18/js/dataTables.bootstrap4.min.js' %}" integrity="" ></script>
    <script src="{% static 'datatable/Buttons-1.5.2/js/dataTables.buttons.min.js' %}" integrity=""  ></script>
    <script src="{% static 'datatable/Buttons-1.5.2/js/buttons.flash.min.js' %}" integrity=""  ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" integrity=""  ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js" integrity=""  ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js" integrity=""  ></script>
    <script src="{% static 'datatable/Buttons-1.5.2/js/buttons.html5.min.js' %}" integrity="" ></script>
   <script src="{% static 'datatable/Buttons-1.5.2/js/buttons.print.min.js' %}" integrity="" ></script>


  <script type="text/javascript">
      $(document).ready(function() {
    $('#review_talk').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            { extend:'copy', attr: { id: 'allan' } }, 'csv', 'excel', 'pdf', 'print'
        ]

    } );
} );
  </script>
{% endblock %}