newnaijalatest/Gist/urls.py
from django.urls import path
from . import views

app_name = 'Gist'

urlpatterns = [
    path('gossip', views.gossip, name='gossip'),
    path('relationship', views.relationship, name='relationship'),
    path('celeb', views.celeb, name='celeb'),
    path('wedding', views.wedding, name='wedding'),
    path('all_gist', views.all_gist, name='all_gist'),
    path('display_gist/<slug>/', views.display_gist, name='display_gist'),
    path('<int:gist_id>/', views.saveviewd, name='save'),
    path('add-gist', views.add_gist, name='add-gist'),
    path('unpublished', views.unpublished_guest, name='unpublished'),
    path('edit_gist/<int:pk>/', views.edit_gist, name='edit_gist')
    ]

newnaijalatest/Music/urls.py
from django.urls import path
from . import views

app_name = 'Music'

urlpatterns = [
    path('newsticker', views.newsticker, name='newsticker'),
    path('home', views.home, name='home'),
    path('', views.home1, name='home1'),
    path('testing', views.testing, name='testing'),
    path('songs', views.songs, name='songs'),
    path('gospel', views.gospel, name='gospel'),
    path('hip_hop_rap', views.hip_hop_rap, name='hip_hop_rap'),
    path('hiphop_pop', views.hiphop_pop, name='hiphop_pop'),
    path('others', views.others, name='others'),
    path('video', views.video, name='video'),
    path('video_gospel', views.video_gospel, name='video_gospel'),
    path('video_hiphop_rap', views.video_hiphop_rap, name='video_hiphop_rap'),
    path('video_hiphop_pop', views.video_hiphop_pop, name='video_hiphop_pop'),
    path('video_others', views.video_others, name='video_others'),
    path('song_download/<slug>/', views.song_download, name='song_download'),
    path('video_download/<slug>/', views.video_download, name='video_download'),
    path('video_download/<slug>/', views.video_download, name='video_download'),
    path('add_music', views.add_music, name='add-music'),
    path('add_audio/<music_id>', views.add_audio, name='add-audio'),
    path('Add Video/<music_id>', views.add_video, name='add-video'),
    path('add_mixtape', views.add_mixtape, name='add_mixtape'),
    path('mixtape', views.mixtape, name='mixtape'),
    path('music_mixtape/<slug>/', views.play_mixtape, name='music_mixtape'),
    path('save_commment', views.save_comment, name='save_comment'),
    path('commment', views.display_comment, name='display_comment'),
    path('unplished_mixtape', views.unpublished_mixtape, name='unpublished_mixtape'),
    path('edit_news/<int:pk>/', views.edit_mixtape, name='Detailview'),
    path('unpublished_music', views.unpublished_music, name='unpublished_music'),
    path('edti_music/<int:pk>/', views.edit_music, name='edit_music'),
    path('unpublished_audio', views.unpublished_audio, name='unpublished_audio'),
    path('edti_audio/<int:pk>/', views.edit_audio, name='edit_audio'),
    path('unpublished_video', views.unpublished_video, name='unpublished_video'),
    path('edit_video/<int:pk>/+', views.edit_video, name='edit_video'),
    path('audiocount', views.audiocount, name='audiocount'),
    path('testes', views.debf.as_view(), name='debf')


]

newnaijalatest/Mysteries/urls.py
from django.urls import path
from . import views

app_name = 'Mysteries'

urlpatterns = [
    path('quotes', views.quotes, name='quotes'),
    path('letters', views.letter, name='letters'),
    path('poem', views.poem, name='poem'),
    path('soul-awakening', views.soul_awakening, name='soul-awakening'),
    path('add_mysteries', views.add_mysteries, name='add_mysteries'),
    path('unpublished', views.unpublished_mystery, name='unpublished'),
    path('edit_mystery/<int:pk>/', views.edit_mystery, name='Detailview')
    ]

newnaijalatest/NaijaLatest/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('__debug__/', include(debug_toolbar.urls)),
    path('Frontend/', include('Frontend.urls')),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('', include('Music.urls')),
    path('Gist/', include('Gist.urls')),
    path('News/', include('News.urls')),
    path('Profile/', include('Profile.urls')),
    path('oauth', include('social_django.urls', namespace='social')),
    path('TalkZone', include('TalkZone.urls')),
    path('Mysteries', include('Mysteries.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('ads/', include('ads.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ]+ urlpatterns

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newnaijalatest/News/urls.py
from django.urls import path
from . import views

app_name = 'News'

urlpatterns = [
    path('politics', views.politics, name='politics'),
    path('sport', views.sport, name='sport'),
    path('entertainment', views.entertainment, name='entertainment'),
    path('all_news', views.all_news, name='all_news'),
    path('display_news/<slug>/', views.display_news, name='display_news'),
    path('addnews', views.add_news, name='addnews'),
    path('review_new', views.unpublished_news, name='review_news'),
    path('edit_news/<int:pk>/', views.edit_news, name='Detailview')
    ]

newnaijalatest/Profile/urls.py
from django.urls import path, include, re_path
from . import views
from social_django.urls import app_name as name
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib import admin
from social_core.utils import setting_name
app_name = 'Profile'
NAMESPACE = getattr(settings, setting_name('URL_NAMESPACE'), None) or 'social'

urlpatterns = [
    #path('login', auth_views.login, name='login'),
    path('oauth', include('social_django.urls', namespace='social')),
    path('dashboard', views.dashboard, name='dashboard'),
    path('profile', views.profile, name='profile'),
    path('sign_up_with_confirmation_mail', views.sign_up_with_confirmation_mail, name='sign_up_with_confirmation_mail'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
            name='activate'),
    path('account_activation_invalid', views.account_activation_invalid, name='account_activation_invalid'),
    path('account_activation_sent', views.account_activation_sent, name='account_activation_sent'),
    path('login', views.login, name='login'),
    path('loginn', views.loginn, name='signin'),
    path('logout', views.logout_view, name='logout'),
    path('test', views.text, name='test'),
    path('status/search_status/', views.search_status, name='search'),
    path('ajax_calls/search/', views.autocomplete, name='autocomplete'),
    path('profile/', views.choose_profile, name='choose_profile'),
    #path('user-dashboard', views.user_dashboard, name='user-dashboard'),
    path('superuser', views.superuser, name='superuser'),
    path('special_user', views.special_user, name='special_user'),
    path('viewers', views.viewers, name='viewers'),
    path('permission', views.permission, name='permission'),
    path('access', views.display_user_type, name='access'),
    path('add_user', views.add_user, name='add_user'),
    path('user_type', views.change_user_type, name='change_user_type'),
    path('delete_user', views.delete_user, name='delete_user'),
    path('password_reset_form', views.password_forgot, name='password_reset_form'),
    path('password_reset', views.password_reset, name='reset_password'),
    path('password_reset_email', views.password_reset_email, name='password_reset_email'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.change_password, name='change_password'),
    path('edit_user_profile', views.edit_user_profile, name='edit_user_profile')
    ]

newnaijalatest/TalkZone/urls.py
from django.urls import path
from . import views

app_name = 'TalkZone'

urlpatterns = [
    path('talkzone', views.talk_zone, name='talkzone'),
    path('talk_zone_view/<slug>/', views.talk_zone_view, name='talk_zone_view'),
    path('Comment', views.save_comment, name='save_comment'),
    path('commment', views.display_comment, name='display_comment'),
    path('index', views.index, name='index'),
    path('lazy_load_posts', views.lazy_load_posts, name='lazy_load_posts'),
    path('add_talk', views.add_talk, name='add_talk'),
    path('unpublished', views.unpublished_talkzone, name='unpublished'),
    path('edit_talkzone/<int:pk>/', views.edit_talk, name='Detailview')
     ]

newnaijalatest/Profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings

def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.username, filename)


class Profile(models.Model):
    address = models.CharField(max_length=250)
    contact_number = models.CharField(max_length=12)
    profile_picture = models.FileField(upload_to='cover_image')


class ProfilePic(models.Model):
    picture = models.FileField(upload_to=user_directory_path)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='picture', on_delete=models.DO_NOTHING)
    upload_date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user_type = models.CharField(default='Temp_User', max_length=20)

newnaijalatest/Profile/forms.py
from django import forms
from .models import Profile
#from Profile.validator import file_size
from django.core.files.images import get_image_dimensions
from django.contrib import admin
from django import forms
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


#class myForm(forms.ModelForm):
   #class Meta:
       #model = myModel
   #def clean_picture(self):
       #picture = self.cleaned_data.get("picture")
       #if not picture:
           #raise forms.ValidationError("No image!")
       #else:
          # w, h = get_image_dimensions(picture)
           #if w != 100:
               #raise forms.ValidationError("The image is %i pixel wide. It's supposed to be 100px" % w)
          # if h != 200:
               #raise forms.ValidationError("The image is %i pixel high. It's supposed to be 200px" % h)
       #return picture


class ProfilePic(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('address', 'contact_number', 'profile_picture')

        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'contact_number': forms.TextInput(attrs={'class': 'form-control'}),
            'profile_picture': forms.FileInput(attrs={'class': 'form-control', 'required':False}),
        }

        def clean_content(self):
            content = self.cleaned_data['profile_picture']
            content_type = content.content_type.split('/')[0]
            if content_type in settings.CONTENT_TYPES:
                if content.size > settings.MAX_UPLOAD_SIZE:
                    raise forms.ValidationError(_('Please keep filesize under %s. Current filesize %s') % (
                    filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(content.size)))
            else:
                raise forms.ValidationError(_('File type is not supported'))
            return content

    """def clean_picture(self):
        profile_picture = self.cleaned_data.get("profile_picture")
        if not profile_picture:
            raise forms.ValidationError("No image!")
        else:
            w, h = get_image_dimensions(profile_picture)
            if w != 100:
                raise forms.ValidationError("The image is %i pixel wide. It's supposed to be 100px" % w)
            if h != 200:
                raise forms.ValidationError("The image is %i pixel high. It's supposed to be 200px" % h)
        return profile_picture"""

newnaijalatest/Profile/templates/Profile/permission.html
{% extends 'backend/base.html' %}
 {% block title %}User Permission{% endblock %}

{% block body %}
{% load static %}
<div class="container">
    <div class="col-sm-10 offset-1">
    <div class="row">
            <div class="col-md-8 offset-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible" role="alert" style="background-color: black; box-shadow: 10px 10px 10px;color:darkgray">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <p style="color:white">{{ message }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
        </div>
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-12">
                      <h3 style="text-align: center">
                          User Priority
                      </h3>
                    </div>
                </div>
                <div class="card-body">
                   <div class="row">
                   <!----- View user---->
                    <div class="col-sm-6">
                        <h4 style="text-align: center">User's in Viewer</h4>
                       {% if viewer %}
                        <table class="table table-striped table-hover" id="group-table" style="margin-top: 2%">
                             <tbody id="thead">
                             {% for users in viewer %}
                             <tr>
                                 <td>{{ users.username }}</td>
                             </tr>
                             {% endfor %}
                             </tbody>
                         </table>
                       {% endif %}
                    </div>
                       <div class="col-sm-6">
                        <h4>User's in Special User</h4>
                        {% if staff %}
                            <table class="table table-striped table-hover" id="group-table" style="margin-top: 2%">
                                 <tbody id="thead">
                                 {% for users in staff %}
                                 <tr>
                                     <td>{{ users.username }}</td>
                                 </tr>
                                 {% endfor %}
                                 </tbody>
                             </table>
                          {% endif %}
                    </div>
                   </div>
                <hr>
                    <div class="row">
                        <div class="col-sm-6">
                          <h4 style="text-align: center">Add User to Special User</h4>
                            <form class="form-group" method="post" action="{% url 'Profile:add_user' %}">
                            {% csrf_token %}
                                <div class="col-sm-6">
                                <label>Select User </label><br>

                                <select name="users" id="id_songs" class="form-control">
                                    {% for es in user %}
                                        <option value="{{ es.id }}">{{ es.username }}</option>
                                    {% endfor %}
                                </select><br>
                                </div>
                                 <div class="col-sm-10">
                                          {% for groups in group %}
                                          <input type="radio" name="Special_Users" value="{{ groups.name }}" style="margin-left: 10%">{{ groups.name }}

                                        {% endfor %}
                                 </div>
                                      <div class="col-lg-6">
                                    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit" style="background-color: white">Create</button>
                                          </div>
                            </form>
                        </div>
                        <div class="col-sm-6">
                            <h4 style="text-align: center">Delete User fro Group</h4>
                            <form class="form-group" method="post" action="{% url 'Profile:delete_user' %}">
                            {% csrf_token %}
                                      <div class="col-sm-6">
                                <label>Delete User </label><br>

                                <select name="deleteuser" id="id_deleteuser" class="form-control">
                                    {% for es in user %}
                                        <option value="{{ es.id }}">{{ es.username }}</option>
                                    {% endfor %}
                                </select><br>
                                      </div>
                                      <div class="col-sm-10">
                                          {% for groups in group %}
                                          <input type="radio" name="Special_Users" value="{{ groups.name }}" style="margin-left: 10%">{{ groups.name }}

                                        {% endfor %}
                                      </div>
                                      <div class="col-lg-6">
                                    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit" style="background-color: white">Delete</button>
                                          </div>
                            </form>
                        </div>
                    </div>
                </div>
             </div>
         </div>
    </div>
</div>

{% endblock %}

newnaijalatest/Profile/templates/Profile/superuser_dashboard.html
{% extends 'backend/base.html' %}
{% load static %}

{% block title %}Super User Dashboard {% endblock %}

{% block css %}

{% endblock %}

{% block body %}
     <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
     <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <!---<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" >--->
<link rel="stylesheet" href="{% static 'datatable/Buttons-1.5.2/css/buttons.dataTables.min.css' %}" >

  <div class="row">
            <div class="col-md-8 offset-2">
                {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" style="background-color: black; box-shadow: 10px 10px 10px;color:darkgray">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    <p style="color:white">{{ message }}</p>
            {% endfor %}
            </div>
        </div>
        </div>
<div class="col-lg-12">
<div class="row" style="margin-top: 2%">
    <div class="col-md-3 offset-md-4" style="background-color: black; border-radius: 5px">
        <h3 style="color: white; text-align: center">UPLOADED AUDIO</h3>
    </div>
</div>
<div class="row" style="margin-top: 1%;box-shadow: 10px 10px 10px">

            {% if user_uploaded_song%}
                <table  id="example" class="display" style="width:100%">
                <thead>
                <tr>
                    <th>Artist</th>
                    <th>Song Title</th>
                    <th>Album</th>
                    <th>Featured Artist</th>
                    <th>Released Year</th>
                    <th>Edit</th>

                </tr>
                </thead>
                <tbody>
                {% for audio in user_uploaded_song  %}
                    <tr>
                    <td>{{ audio.music.artist| safe }}</td>
                    <td>{{ audio.music.song_title| safe }}</td>
                    <td>{{ audio.music.album| safe }}</td>
                    <td>{{ audio.music.featured_artist| safe}}</td>
                     <td>{{ audio.music.released_Year }}</td>
                    <td><a href="{% url 'Music:edit_audio' audio.id %}" class="btn btn-primary btn-sm" role="button"><i class="far fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>

        {% else %}
    <P>no data found</P>
{% endif %}
        </div>
<div class="row" style="margin-top: 2%;">
    <div class="col-md-3 offset-md-4" style="background-color: black; border-radius: 5px">
        <h3 style="color: white; text-align: center">UPLOADED VIDEO</h3>
    </div>
</div>
<div class="row" style="margin-top: 1%;box-shadow: 10px 10px 10px">

            {% if  user_uploaded_video %}
                <table  id="video" class="display" style="width:100%">
                <thead>
                <tr>
                    <th>Artist</th>
                    <th>Song Title</th>
                    <th>Album</th>
                    <th>Featured Artist</th>
                    <th>Released Year</th>
                    <th>Edit</th>

                </tr>
                </thead>
                <tbody>
                {% for video in  user_uploaded_video   %}
                    <tr>
                    <td>{{ video.music.artist| safe }}</td>
                    <td>{{ video.music.song_title| safe }}</td>
                    <td>{{ video.music.album| safe }}</td>
                    <td>{{ video.music.featured_artist| safe}}</td>
                     <td>{{ video.music.released_Year }}</td>
                     <td><a href="{% url 'Music:edit_video'  video.id %}" class="btn btn-primary btn-sm" role="button"><i class="far fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>

        {% else %}
    <P>no data found</P>
{% endif %}
        </div>

<div class="row" style="margin-top: 2%;">
    <div class="col-md-3 offset-md-4" style="background-color: black; border-radius: 5px">
        <h3 style="color: white; text-align: center">UPLOADED GIST</h3>
    </div>
</div>
<div class="row" style="margin-top: 1%;box-shadow: 10px 10px 10px">

            {% if user_uploaded_gist %}
                <table  id="gists" class="display" style="width:100%">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Created Date</th>
                    <th>Edit</th>

                </tr>
                </thead>
                <tbody>
                {% for gist in  user_uploaded_gist   %}
                    <tr>
                    <td>{{gist.title| safe }}</td>
                    <td>{{ gist.category | safe}}</td>
                    <td>{{ gist.created_on | date }}</td>
                    <td><a href="{% url 'Gist:edit_gist' gist.id %}" class="btn btn-primary btn-sm" role="button"><i class="far fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>

        {% else %}
    <P>no data found</P>
{% endif %}
        </div>
<div class="row" style="margin-top: 2%;">
    <div class="col-md-3 offset-md-4" style="background-color: black; border-radius: 5px">
        <h3 style="color: white; text-align: center">UPLOADED TALK ZONE</h3>
    </div>
</div>
 {% if user_uploaded_talk %}
<div class="row" style="margin-top: 1%;box-shadow: 10px 10px 10px">


                <table  id="talk" class="display" style="width:100%">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Poster</th>
                    <th>Created Date</th>
                    <th>Edit</th>

                </tr>
                </thead>
                <tbody>
                {% for talk in  user_uploaded_talk  %}
                    <tr>
                    <td>{{talk.title| safe }}</td>
                    <td>{{ talk.poster | safe }}</td>
                    <td>{{ talk.created_on | date }}</td>
                    <td><a href="{% url 'TalkZone:Detailview' talk.pk %}" class="btn btn-primary btn-sm" role="button"><i class="far fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
        </div>
{% endif %}

<div class="row" style="margin-top: 2%;">
    <div class="col-md-3 offset-md-4" style="background-color: black; border-radius: 5px">
        <h3 style="color: white; text-align: center">UPLOADED NEWS</h3>
    </div>
</div>
<div class="row" style="margin-top: 1%;box-shadow: 10px 10px 10px">
{% if user_uploaded_news %}

                <table  id="newss" class="display" style="width:100%">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Created Date</th>
                    <th>Edit</th>

                </tr>
                </thead>
                <tbody>
                {% for news in  user_uploaded_news %}
                    <tr>
                    <td>{{news.title| safe }}</td>
                    <td>{{ news.category| safe }}</td>
                    <td>{{ news.created_on | date }}</td>
                     <td><a href="{%  url 'News:Detailview' news.id %}" class="btn btn-primary btn-sm" role="button"><i class="far fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>

        {% else %}
    <P>no data found</P>
{% endif %}
    </div>

<!-------------------Mystery---------------------------------------------->

<div class="row" style="margin-top: 2%;">
    <div class="col-md-3 offset-md-4" style="background-color: black; border-radius: 5px">
        <h3 style="color: white; text-align: center">MYSTERIES</h3>
    </div>
</div>
<div class="row" style="margin-top: 1%;box-shadow: 10px 10px 10px">
{% if user_uploaded_mystery %}

                <table  id="myst" class="display" style="width:100%">
                <thead>
                <tr>
                    <th>Category</th>
                    <th>Author</th>
                    <th>Created Date</th>
                    <th>Edit</th>
                </tr>
                </thead>
                <tbody>
                {% for mystery in  user_uploaded_mystery %}
                    <tr>
                    <td>{{mystery.category| safe  }}</td>
                    <td>{{ mystery.author | safe }}</td>
                    <td>{{ mystery.created_date| date }}</td>
                     <td><a href="{%  url 'Mysteries:Detailview' mystery.id %}" class="btn btn-primary btn-sm" role="button"><i class="far fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>

        {% else %}
    <P>no data found</P>
{% endif %}
    </div>

<!-------------------Mixtape---------------------------------------------->

<div class="row" style="margin-top: 2%;">
    <div class="col-md-3 offset-md-4" style="background-color: black; border-radius: 5px">
        <h3 style="color: white; text-align: center">MIXTAPE</h3>
    </div>
</div>
<div class="row" style="margin-top: 1%;box-shadow: 10px 10px 10px">

{% if user_uploaded_mixtape %}
                <table  id="mix" class="display" style="width:100%">
                <thead>
                <tr>
                    <th>Tape Name</th>
                    <th>Dj Name</th>
                    <th>Created Date</th>
                    <th>Edit</th>
                </tr>
                </thead>
                <tbody>
                {% for tapes in  user_uploaded_mixtape %}
                    <tr>
                    <td>{{tapes.tape_name| safe  }}</td>
                    <td>{{tapes.dj_name | safe }}</td>
                    <td>{{ tapes.uploaded_at | date }}</td>
                     <td><a href="{%  url 'Music:Detailview' tapes.id %}" class="btn btn-primary btn-sm" role="button"><i class="far fa-edit"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>

        {% else %}
    <P>no data found</P>
{% endif %}
    </div>

</div>


   <!--<script src="https://code.jquery.com/jquery-3.3.1.js" integrity=""></script>
     <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>--->

    <script src="{% static 'datatable/DataTables-1.10.18/js/jquery.dataTables.min.js' %}" integrity="" ></script>
    <script src="{% static 'datatable/DataTables-1.10.18/js/dataTables.bootstrap.min.js' %}" integrity="" ></script>
    <script src="{% static 'datatable/DataTables-1.10.18/js/dataTables.bootstrap4.min.js' %}" integrity="" ></script>
    <script src="{% static 'datatable/Buttons-1.5.2/js/dataTables.buttons.min.js' %}" integrity=""  ></script>
    <script src="{% static 'datatable/Buttons-1.5.2/js/buttons.flash.min.js' %}" integrity=""  ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" integrity=""  ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js" integrity=""  ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js" integrity=""  ></script>
    <script src="{% static 'datatable/Buttons-1.5.2/js/buttons.html5.min.js' %}" integrity="" ></script>
   <script src="{% static 'datatable/Buttons-1.5.2/js/buttons.print.min.js' %}" integrity="" ></script>


  <script type="text/javascript">
      $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            { extend:'copy', attr: { id: 'allan' } }, 'csv', 'excel', 'pdf', 'print'
        ]

    } );
} );
  </script>
    <script type="text/javascript">
      $(document).ready(function() {
    $('#video').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            { extend:'copy', attr: { id: 'allan' } }, 'csv', 'excel', 'pdf', 'print'
        ]

    } );
} );
  </script>
     <script type="text/javascript">
      $(document).ready(function() {
    $('#gists').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            { extend:'copy', attr: { id: 'allan' } }, 'csv', 'excel', 'pdf', 'print'
        ]

    } );
} );
  </script>
    <script type="text/javascript">
      $(document).ready(function() {
    $('#newss').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            { extend:'copy', attr: { id: 'allan' } }, 'csv', 'excel', 'pdf', 'print'
        ]

    } );
} );
  </script>
    <script type="text/javascript">
      $(document).ready(function() {
    $('#talk').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            { extend:'copy', attr: { id: 'allan' } }, 'csv', 'excel', 'pdf', 'print'
        ]

    } );
} );
  </script>
       <script type="text/javascript">
      $(document).ready(function() {
    $('#mix').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            { extend:'copy', attr: { id: 'allan' } }, 'csv', 'excel', 'pdf', 'print'
        ]

    } );
} );
  </script>
     <script type="text/javascript">
      $(document).ready(function() {
    $('#myst').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            { extend:'copy', attr: { id: 'allan' } }, 'csv', 'excel', 'pdf', 'print'
        ]

    } );
} );
  </script>
{% endblock %}

{% block js %}

{% endblock %}